Repository openshift/splunk-forwarder-operator, pull requests merged in 2019-11, with the labels that each got.

#6 Forwarder image cleanup and work on the olm-artifacts-template
  deploy/crds/splunkforwarder_v1alpha1_splunkforwarder_cr.yaml
  deploy/crds/splunkforwarder_v1alpha1_splunkforwarder_crd.yaml
  forwarder/Dockerfile
  hack/app_sre_build_deploy.sh
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/apis/splunkforwarder/v1alpha1/splunkforwarder_types.go
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
  pkg/kube/configmaps.go
  standard.mk
Labels: approved, lgtm, size/M

#8 Update dockerfile to be inline with what we use for other OSD operators
  build/Dockerfile
Labels: approved, lgtm, size/S

#9 Fix spacing on FORWARDER_VERSION and FORWARDER_HASH
  hack/app_sre_build_deploy.sh
Labels: approved, lgtm, size/XS

#10 Fix errors in app_sre_build_deploy.sh
  hack/app_sre_build_deploy.sh
Labels: approved, lgtm, size/XS

#11 Fix path issue for forwarder version
  hack/app_sre_build_deploy.sh
Labels: approved, lgtm, size/XS

#12 Fix which files are included in the CSV
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/S

#13 Remove CR from olm for now
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#14 Add the splunk forwarder CR back
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#15 Create SelectorSyncSet to deploy to clusters
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/L

#16 Give the SSS different names
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#17 Fix namespaces for the catalog, operator group, and subscription
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#18 Create the openshift-splunk-forwarder-operator ns and cluster role
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/M

#19 Fix several issues around the operator deploying.
  cmd/manager/main.go
  config/templates/splunk-forwarder-operator-csv-template.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#20 Fix indention of old artifact
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#21 Update the api group name for the rbac policy
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#22 Minor fixes
  forwarder/Dockerfile
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/kube/volumemounts.go
Labels: approved, lgtm, size/M

#24 Fix error in the SCC
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#25 Enable logging for when it cannot get the infra config
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
Labels: approved, lgtm, size/XS

#26 Register the openshift config types
  cmd/manager/main.go
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
Labels: approved, lgtm, size/S

#27 Fix cluster role for config.openshift.io infrastructure
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#28 Fix resource name and add watch to the verbs
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#29 Find the clusterid and pass it in to the configmap
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
  pkg/kube/configmaps.go
Labels: approved, lgtm, size/S

#7 Add LICENSE file
  LICENSE
Labels: approved, lgtm, size/L

#30 Use status.infrastructurename instead of clustername
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
Labels: approved, lgtm, size/XS

#31 Update docs
  README.md
  deploy/crds/splunkforwarder_v1alpha1_splunkforwarder_cr.yaml
Labels: approved, lgtm, size/S

#32 Update debug node log path
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#33 Node debug logs are not json
  deploy/crds/splunkforwarder_v1alpha1_splunkforwarder_cr.yaml
Labels: approved, lgtm, size/XS

#34 Update the OLM artifact template to also have the custom source type
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#35 CR is case sensitive
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#36 Store the CR generation and compare during reconcile
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
  pkg/kube/configmaps.go
  pkg/kube/daemonset.go
Labels: approved, lgtm, size/M

#37 Fix _meta syntax
  pkg/kube/configmaps.go
Labels: approved, lgtm, size/XS

#38 Rollout to all managed clusters
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#39 Add kube apiserver audit.log
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#40 Add logging around the operator
  pkg/controller/splunkforwarder/splunkforwarder_controller.go
Labels: approved, lgtm, size/S

#41 Use strconv.FormatInt() over string()
  pkg/kube/configmaps.go
  pkg/kube/daemonset.go
Labels: approved, lgtm, size/S

#43 Add different CRs based on environment
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/M

#44 matchLabels is not an array
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS
